tables:
  - name: info
    count: 10
    action: generate
    fields:
      id:
        type: int
        generation: db
      phone:
        type: phone
        generation: faker
      address:
        type: address
        generation: faker
      user_id:
        type: int
        generation: depends
        depends:
          foreign:
            - db: main
              table: users
              field: id
  - name: users
    count: 10
    action: generate
    fields:
      id:
        type: int
        generation: db
      username:
        type: string
        generation: faker
      password:
        type: string
        generation: faker
        plugins:
          - bcrypt
      last_online:
        type: "date 2022-01-01"
        generation: faker
      area_id:
        type: int
        generation: depends
        depends:
          foreign:
            - db: main
              table: areas
              field: id
    fill:
      - username: admin
        password: admin
  - name: roles
    count: 2
    action: generate
    fields:
      id:
        type: int
        generation: db
      name:
        type: string
        generation: list
        list:
          - ROLE_ADMIN
          - ROLE_USER
    fill:
      - name: ROLE_ADMIN
      - name: ROLE_USER
  - name: user_in_roles
    count: 10
    action: generate
    fields:
      user_id:
        type: int
        generation: depends
        depends:
          foreign:
            - db: main
              table: users
              field: id
      role_id:
        type: int
        generation: depends
        depends:
          foreign:
            - db: main
              table: roles
              field: id