databases:
  main:
    name: main
    driver: "pgx"
    dsn: "host=localhost port=15434 user=admin password=admin dbname=admin sslmode=disable"
    tablesPath: "$PWD/main"
#  main:
#    name: main
#    driver: "mysql"
#    dsn: "admin:admin@localhost:13306/admin"
#    tablesPath: "$PWD/main"
