package schema

import (
	"gopkg.in/yaml.v3"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

type Action string
type Generation string
type ForeignKeyType string

const (
	ActionGenerate Action = "generate" // Generate list of values for insert to db
	ActionGet      Action = "get"      // Get list of values from db

	GenerationTypeDb    Generation = "db"      // Data will be generated by DB for example auto_increment and so on
	GenerationTypeFaker Generation = "faker"   // Generate fake data
	GenerationTypeList  Generation = "list"    // Get data from defined list (property List of Field struct)
	GenerationDepends   Generation = "depends" // Mark field that it depends on another field (on same ot other table)

	ManyToOne ForeignKeyType = "manyToOne"
	OneToOne  ForeignKeyType = "oneToOne"
)

type Databases struct {
	Databases map[string]*Database `json:"databases" yaml:"databases"`
}

type Database struct {
	Driver     string  `json:"driver" yaml:"driver"`
	Name       string  `json:"name" yaml:"name"` // Database name
	DSN        string  `json:"dsn" yaml:"dsn"`   // Database DSN
	TablesPath string  `json:"tables_path" yaml:"tablesPath"`
	Tables     []Table `json:"tables" yaml:"tables"`
}

type Table struct {
	/// TODO: Add unique values block
	NoDuplicates bool             `json:"no_duplicates" yaml:"noDuplicates"` // Allow duplicates or no
	Count        int              `json:"count" yaml:"count"`                // Count rows for generate values
	Name         string           `json:"name" yaml:"name"`                  // Table name
	Action       Action           `json:"action" yaml:"action"`              // Action (get from db or generate fake data)
	Fields       map[string]Field `json:"fields" yaml:"fields"`
	Fill         []map[string]any `json:"fill" yaml:"fill"`
}

func (t *Table) GetRowsCount() int {
	if t.Count <= 0 {
		if len(t.Fill) <= 0 {
			return 0
		} else {
			return len(t.Fill)
		}
	}

	return t.Count
}

func (t *Table) IsLoadFromDb() bool {
	return t.Action == ActionGet
}

type Field struct {
	Type       string     `json:"type" yaml:"type"`             // Type of field - string, email, hash, mac, ip and so on... See types constants
	Generation Generation `json:"generation" yaml:"generation"` // Generation strategy
	Plugins    []string   `json:"plugins" yaml:"plugins"`       // Plugins list for apply
	Depends    Dependence `json:"depends" yaml:"depends"`
	List       []any      `json:"list" yaml:"list"`
}

func (fld *Field) IsFkDependence() bool {
	return fld.Depends.ForeignKey.Db != "" && fld.Depends.ForeignKey.Table != "" && fld.Depends.ForeignKey.Field != ""
}

func (fld *Field) IsExpressionDependence() bool {
	return fld.Depends.Expression.Expression != ""
}

type Dependence struct {
	Expression ExpressionDependence `json:"expression" yaml:"expression"`
	ForeignKey ForeignDependence    `json:"foreign_key" yaml:"foreign"`
}

type ForeignDependence struct {
	Db    string         `json:"db" yaml:"db"`
	Table string         `json:"table" yaml:"table"`
	Field string         `json:"field" yaml:"field"`
	Type  ForeignKeyType `json:"type" yaml:"type"`
}

type ExpressionDependence struct {
	Expression string   `yaml:"expression" json:"expression"`
	Rows       []string `json:"rows" yaml:"rows"`
}

type ExpressionForeignField struct {
	Db    string `json:"db" yaml:"db"`
	Table string `json:"table" yaml:"table"`
	Field string `json:"field" yaml:"field"`
}

func NewDatabasesSchemaNotation(mainConf string) (*Databases, error) {
	cfg := &Databases{}
	dbData, readFileErr := os.ReadFile(mainConf)
	if readFileErr != nil {
		return nil, readFileErr
	}
	unmarshalErr := yaml.Unmarshal(dbData, cfg)
	if unmarshalErr != nil {
		return nil, unmarshalErr
	}

	for id, d := range cfg.Databases {
		if d.TablesPath != "" {
			d.TablesPath = strings.ReplaceAll(d.TablesPath, "$PWD", filepath.Dir(mainConf))

			walkErr := filepath.Walk(d.TablesPath, func(path string, info fs.FileInfo, err error) error {
				if err != nil {
					return err
				}
				if info.IsDir() {
					return nil
				}
				tableData, tableFileReadErr := os.ReadFile(path)
				if tableFileReadErr != nil {
					return tableFileReadErr
				}
				type t struct {
					Tables []Table `json:"tables" yaml:"tables"`
				}

				tbl := &t{}
				tableUnmarshalErr := yaml.Unmarshal(tableData, tbl)
				if tableUnmarshalErr != nil {
					return tableUnmarshalErr
				}
				d.Tables = append(d.Tables, tbl.Tables...)

				return nil
			})
			if walkErr != nil {
				return nil, walkErr
			}
			cfg.Databases[id] = d
		}
	}

	return cfg, nil
}
